#!/usr/bin/with-contenv bash

mkdir -p /data/filebot/logs /data/qBittorrent

if [ ! -f /data/qBittorrent/qBittorrent.conf ]; then cp /src/qBittorrent.conf /data/qBittorrent ; fi

#if user customized, don't touch it
script=/data/filebot/fb.sh
if [ -f "$script" ] && [ ! -z $(grep "custom=1" "$script") ]; then :; else cp /src/fb.sh /data/filebot; fi

# Check config AutoRun:
if [[ $(comm -13 <(sort -u /data/qBittorrent/qBittorrent.conf) <(sort -u /src/check)) ]]; then cp /src/qBittorrent.conf /data/qBittorrent/qBittorrent.conf ; fi

# Set the license:
license=$(find /data/ -iname "*.psm" | head -n1)
if ! [ -z "${license}" ];
   then sh /filebot/filebot.sh --license=${license}
else
   echo -e "#####\n#\n#>> No license detected for FILEBOT.\n#>> Plz put you license psm file in /data/filebot folder\n#\n#\n#####"
fi

# Set extra filebot parameters
if ! [ -z "${EXTRA_FILEBOT_PARAM}" ];
then
  sed -i '/output/a "${EXTRA_FILEBOT_PARAM}" \\' /data/filebot/fb.sh
else
  sed -i '/EXTRA_FILEBOT_PARAM/d' /data/filebot/fb.sh
fi

# Futur feature
# Clear the status of opensubtitles
#rm /filebot/osdb.loggedin 2> /dev/null



# Fix some permissions:
chown -R ${PUID}:${PGID} \
        /usr/local/bin \
        /data \
	/filebot
chmod +x /data/filebot/fb.sh

# Check files permssions if asked (default is no):
# Be aware that it can take long time if you have a big /media folder
# and then you' ll have to wait before you get the web interface of qbittorrent !
if [[ ${FILES_CHECK_PERM} =~ [yY] ]]; then chown -R ${PUID}:${PGID} /media ; fi

exit
